-- CHECK BANG 1
CREATE TABLE SANPHAM
(
  MASP			NVARCHAR(10) NOT NULL,
  HDH			NVARCHAR(20) NOT NULL,
  HANGSX		NVARCHAR(20),
  TENSP			NVARCHAR(20) NOT NULL,
  MANHINH		NVARCHAR(20) NOT NULL,
  CPU			NVARCHAR(20) NOT NULL, -- CPU la co chip vd 13,1215U,1.2GHz
  RAM			NVARCHAR(20) NOT NULL,
  OCUNG			NVARCHAR(20) NOT NULL,
  PIN			NVARCHAR(20) NOT NULL,
  THOIDIEMRAMAT DATETIME,
  CARDMANHINH   NVARCHAR(20) NOT NULL,
  KICHTHUOC		INT,
  KHOILUONG		INT,
  PRIMARY KEY (MASP)
);
-- CHECK BANG 2
CREATE TABLE KHACHHANG
(
  MAKH			NVARCHAR(10) NOT NULL,
  EMAIL			NVARCHAR(20) ,
  TENKH			NVARCHAR(20) ,
  SDT			NVARCHAR(20) NOT NULL,
  DIACHI		NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MAKH)
);
-- CHECK BANG 3
CREATE TABLE NHACUNGCAP
(
  MANHACC		NVARCHAR(10) NOT NULL,
  TEN			NVARCHAR(20),
  SDT			NVARCHAR(15) NOT NULL,
  EMAIL			NVARCHAR(20),
  DIACHI		NVARCHAR(20),
  PRIMARY KEY (MANHACC)
);
-- CHECK BANG 4
CREATE TABLE NHANVIEN
(
  TENNV			NVARCHAR NOT NULL,
  GIOITINH		BIT,
  NGAYSINH		DATETIME,
  DIACHI		NVARCHAR(30) NOT NULL,
  SDT			NVARCHAR(15) NOT NULL,
  MANV			NVARCHAR(10) NOT NULL,
  PRIMARY KEY (MANV)
);
-- CHECK BANG 5 
CREATE TABLE HOADONNHAP
(
  NGAYNHAP		DATETIME,
  GIAMGIA		INT,
  THANHTIEN		INT,
  SOHOADON		NVARCHAR(10) NOT NULL,
  MANHACC		NVARCHAR(10) NOT NULL,
  MANV			NVARCHAR(10) NOT NULL,
  PRIMARY KEY (SOHOADON),
  FOREIGN KEY (MANHACC) REFERENCES NHACUNGCAP(MANHACC),
  FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
-- CHECK BANG 6
CREATE TABLE HOADONBAN
(
  THANHTIEN		DECIMAL(10,2),
  NGAYBAN		DATETIME,
  SOHD			NVARCHAR(10) NOT NULL,
  MAKH			NVARCHAR(10) NOT NULL,
  MANV			NVARCHAR(10) NOT NULL,
  PRIMARY KEY (SOHD),
  FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
  FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
-- CHECK BANG 7
CREATE TABLE XUATHDN (
    MASP		NVARCHAR(10)	NOT NULL,
    SOHOADON	NVARCHAR(10) NOT NULL,
    DONGIA		INT,
	SL			INT,
    PRIMARY KEY (MASP, SOHOADON),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    FOREIGN KEY (SOHOADON) REFERENCES HOADONNHAP(SOHOADON)
);
-- CHECK BANG 8
CREATE TABLE XUATHDB (
    MASP		NVARCHAR(10) PRIMARY KEY,
	SOHD		NVARCHAR(10),
    DONGIA		INT,
    SL			INT,
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    FOREIGN KEY (SOHD) REFERENCES HOADONBAN(SOHD)
);
